version: "3.8"

services:
    label-studio:
#        container_name: label-studio
        image: heartexlabs/label-studio:develop
        environment:
        - PORT=8080
        - ML_BACKEND=remote
        - ML_BACKEND_URL=http://spacy:9090
        - OPENAI_API_KEY=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
        ports:
        - 8080:8080
        volumes:
        - "./data:/label-studio/data"
        - "./data/server:/data"

    llm:
      container_name: llm
      image: mar1a/llm-interactive:v0
      build: ./llmner
      environment:
        - MODEL_DIR=/data/models
        - OPENAI_API_KEY=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
        - OPENAI_MODEL=gpt-3.5-turbo
#        - PROMPT_TEMPLATE=
        - LOG_LEVEL=DEBUG
        - TEMPERATURE=0.
      ports:
        - 9091:9091
      volumes:
        - "./data/server:/data"

    spacy:
      container_name: spacy
      build: ./spacy
      image: mar1a/spacy:v0
      environment:
        - WORKERS=2
        - THREADS=4
        - LOG_LEVEL=DEBUG
        - MODEL_DIR=/data/models
        - SPACY_MODEL=model_018
      volumes:
        - "./data/server:/data"
      ports:
        - 9090:9090